### ISSUE TITLE
Module 'IzzyParser' Not Found After Migrating from SPM to CocoaPods

### ISSUE THREAD

**Issue by KristjanIzo** [undabot/izzyparser-ios#16]
**Description:**
I recently migrated my project from using Swift Package Manager (SPM) to CocoaPods in order to integrate GoogleMLKit, which required CocoaPods. However, after migrating and installing IzzyParser via CocoaPods, I am encountering the error module 'IzzyParser' not found, even though IzzyParser appears to be correctly installed in the Pods directory.

**Environment:**
- Xcode Version: 15.2
- IzzyParser Version: 1.0.0
- Platform: iOS 12.0

**Steps to Reproduce:**

1. Initially integrated IzzyParser using Swift Package Manager.
2. Migrated the project to use CocoaPods for dependency management.
3. Added IzzyParser to the Podfile and ran pod install.
4. Cleaned the build folder and deleted derived data.
5. Attempted to build the project.

**Podfile Configuration:**
```
platform` :ios, '12.0'

target 'IzoAuth' do
  use_frameworks!
  # Pods for IzoAuth
end

target 'IzoCore' do
  use_frameworks!
  # Pods for IzoCore
end

target 'IzoElektro' do
  use_frameworks!
  pod 'GoogleMLKit/BarcodeScanning'
  pod 'Firebase/Messaging'
  pod 'DGCharts'
  pod 'Kingfisher', '~> 7.0'
  pod 'iOSDFULibrary'
  pod 'iOSMcuManagerLibrary'
  pod 'GoogleToolboxForMac'
end

target 'IzoNetworking' do
  use_frameworks!
  pod 'IzzyParser'
end

target 'Lumber' do
  use_frameworks!
  # Pods for Lumber
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
```

**Troubleshooting Steps Taken:**

1. Verified that `IzzyParser` is listed under the `Pods` project in Xcode.
2. Ensured that `use_frameworks!` is enabled for all targets in the `Podfile`.
3. Updated `Runpath Search Paths` to include `$(inherited)`, `@executable_path/Frameworks`, and `@loader_path/Frameworks`.
4. Cleaned the build folder and deleted derived data.
5. Reinstalled pods using `pod deintegrate` and `pod install`.

**Current Issue:**
Despite following these steps, the error persists, indicating that Xcode is unable to locate the IzzyParser module. 

**Additional Information:**
Screenshots and relevant code snippets are attached for further context.
<img src="https://github.com/undabot/izzyparser-ios/assets/153920466/8138a68d-ef79-415c-a334-872344398ed2" width="300"/>
<img src="https://github.com/undabot/izzyparser-ios/assets/153920466/e02402a0-d7ab-47cd-a9fb-4b74c0372730" width="1000"/>
<img src="https://github.com/undabot/izzyparser-ios/assets/153920466/617dcd11-62ae-40b6-b151-a09097859ca2" width="200"/> <img src="https://github.com/undabot/izzyparser-ios/assets/153920466/e7c891e8-8105-48c1-9c41-b54489f551fa" width="200"/>
<img src="https://github.com/undabot/izzyparser-ios/assets/153920466/40be2ff5-fbef-4ed3-89f5-118fe50fc75a" width="1000"/>

**Request:**
I would appreciate any guidance or suggestions to resolve this issue. If additional configuration or steps are required to correctly integrate IzzyParser via CocoaPods, please provide detailed instructions.

Thank you for your assistance.

**Comment by JFejza** [comment]
@KristjanIzo 

Hi!
Thank you for using IzzyParser in your project. From the configuration steps you have provided I can see you have done everything correctly, yet I can also see the problem. Unfortunately IzzyParser is only available in iOS 14 or higher as it is stated in the Podfile of the example project provided in the repo.

`platform :ios, '14.0'`

If you can please upgrade your project to minimum iOS 14 and IzzyParser will work as expected. 
Thank you!
